#!/usr/bin/env bash

sudo apt update && sudo apt -y upgrade

# cowsay, etc.


# cheat.sh
sudo apt-get install rlwrap xsel -y
curl https://cht.sh/:cht.sh | sudo tee /usr/local/bin/cht.sh
sudo chmod +x /usr/local/bin/cht.sh
